### ISSUE TITLE
No function solve_all_constraints_one_by_one defined

### ISSUE THREAD

**Issue by yech1990** [Edinburgh-Genome-Foundry/DnaChisel#1]
https://github.com/Edinburgh-Genome-Foundry/DnaChisel/blob/50bcd9a4f15228137cfd7f38377ca24eaaa63108/examples/plasmid_optimization.py#L95

**Comment by Zulko** [comment]
Thanks for the report, this example is now fixed on Github (and moved to the "scenarios" subfolder).
