### ISSUE TITLE
Other optimization policies exist?

### ISSUE THREAD

**Issue by yech1990** [Edinburgh-Genome-Foundry/DnaChisel#2]
https://github.com/Edinburgh-Genome-Foundry/DnaChisel/blob/a318ca56f1731c7bffa6322b7648e0e5c237dd9f/dnachisel/builtin_specifications/CodonOptimize.py#L12-L14

**Comment by Zulko** [comment]
There seems to be several accepted ways to optimize codons. Here is an example: In the E. coli genome, the amino acid Glu is encoded by GAA 70% of the time and by GAG 30% of the time. When codon optimizing a gene for E. coli, you can either:

1. Use GAA for Glu, all the time or as much as possible, as this seems to be the preferred amino acid.
2. Use GAA 70% of the time and by GAG 30% of the time, or as close to this as possible.

As of now, DnaChisel implements the strategy (1) only.

Does this answer your question ?

**Comment by yech1990** [comment]
@Zulko 
My question is whether there are options to use strategy(2) or any other strategies.
If not, will it be added in the future release?

**Comment by Zulko** [comment]
They will certainly be in the future. Do you need this feature now ? Or in what time frame ?

**Comment by yech1990** [comment]
@zulko I need this feature now.
I don't think all best codon is the best solution.

**Comment by Zulko** [comment]
I believe this is now adressed with the last commit. The Github version (and soon the PyPI version) now have a parameter ``mode='best_codon'`` or ``mode='harmonized'`` for the specification ``CodonOptimize``. For ``best_codon``, the optimization will always replace a codon with the most-frequent triplet possible. For ``harmonized``, the optimization will bring the relative frequencies of the different triplets as close as possible as the frequencies in the reference species (this is also known as codon harmonization).

Feel free to open no issues if this was not satisfactory.

**Comment by picousse** [comment]
I'm not an expert on this but isn't harmonization mapping over the host codon usage table with the destination host codon usage table? 
and then if e.g. a codon is rare in the original host, it should also be rare in the destination host?

If there is ribosome pausing in the original host, this should then also be the case in the destination host.

As far as I inderstood, the current harmonization algorithm randomly picks a codon, and in the end the distribution over the different codons should be as close as possible with the host codon table? 
Biology wise this seems not interesting. I think it is far more important to mimic the original translational process: ribosome pausing allows for folding of the part that is already transcribed, ...

But to conclude, this would be a nice have, but currently it is not implemented, if I understood correctly?

**Comment by picousse** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2364656/

**Comment by Zulko** [comment]
That makes sense. How would it work in practice (I may not have time for reading through this) ? Is it just replacing the most-used codon in the original host by the most used codon in the target host (and same for second-most used, etc.), then same for second-most used codon, etc. ?

**Comment by picousse** [comment]
Hi,
Sorry, but I'm not the expert here. 
Something like that yes, but I'm afraid that if you don't take any percentages as well into calculation, you could get some weird results.
E.g. Let's say you have codon usage of 80% 10% and 10% in the original host and you would map it purely based on ranking to something like 50%45%5% in the destination host, you're pretty far off... I should dig deeper into these articles and algorithms to exactly know how they work.

A nice database that might come in handy is https://www.kazusa.or.jp/codon/
Or the possibility to feed a genbank file with all protein sequences of an organism (from e.g. ncbi).

**Comment by Zulko** [comment]
Looks cool, would you mind summarizing the principles in this thread ? (I will have a busy week). For the anecdote, Joao Guimaraes wrote a sequence optimizer called D-tailor with cool ideas around 5 years ago. Maybe there will be software associated to this paper too ?

**Comment by ilpepe** [comment]
Hi, indeed they are using D-tailor.
Wasn't aware of that one.
Still reading. Bit jealous on the article. Worth multiple PhD... the amount of data alone...

**Comment by Zulko** [comment]
Thanks for the comment @jjs6w that's very good to know !

**Comment by Zulko** [comment]
Thanks everyone for the contributions, I am closing this as Chisel now has 3 different codon optimization classes ("use best codon", "match target codon usage", and "harmonize codons from host to target, using RCA"). See [this section](https://edinburgh-genome-foundry.github.io/DnaChisel/ref/builtin_specifications.html#codon-optimization-specifications) in the docs.
