### ISSUE TITLE
Why self.sequence = self.sequence_before while doing optimize_by_exhaustive_search?

### ISSUE THREAD

**Issue by Lix1993** [Edinburgh-Genome-Foundry/DnaChisel#21]
https://github.com/Edinburgh-Genome-Foundry/DnaChisel/blob/78043a3bc04cb9c175013fde043555625b613774/dnachisel/DnaOptimizationProblem.py#L570

**Comment by Zulko** [comment]
You are right, this is an oversight. As I understand it, this line does nothing at all actually.

In case you are analyzing the code, just a warning note that I will soon push a v3.x on Github with very re-organized code (same code but different file organization) and some small API changes.

**Comment by Zulko** [comment]
removed in the last update
