### ISSUE TITLE
Raise an error if the codon usage table is not found for the given taxonomy ID

### ISSUE THREAD

**Issue by lebolo** [Edinburgh-Genome-Foundry/DnaChisel#41]
I opened a PR in https://github.com/Edinburgh-Genome-Foundry/codon-usage-tables/pull/4, but I think you're using a custom version of this code? I couldn't find it here. I wonder if it would be possible to raise an error when the usage table for a taxonomy ID isn't available on the kazusa website.

Otherwise, DNA Chisel just spits out a KeyError (codon) somewhere downstream when it looks up the codon in an empty table.

**Comment by veghp** [comment]
Thank you, will look into this and https://github.com/Edinburgh-Genome-Foundry/codon-usage-tables/pull/4

**Comment by veghp** [comment]
Addressed in https://github.com/Edinburgh-Genome-Foundry/codon-usage-tables/pull/4 and https://github.com/Edinburgh-Genome-Foundry/codon-usage-tables/pull/5. Thank you for raising this issue and providing a solution.
