### ISSUE TITLE
Avoid repeats in nucleotide sequence

### ISSUE THREAD

**Issue by lebolo** [Edinburgh-Genome-Foundry/DnaChisel#45]
Hello, a long time ago I think DNA Chisel had an _AvoidRepeat_ spec, but I can't seem to find it anymore.

Is there a way to avoid repeats in the whole nucleotide sequence (e.g. avoid repeats of length 10 - like GGGGGGGGGG or any base - in the entire sequence). I think [UniquifyAllKmers](https://edinburgh-genome-foundry.github.io/DnaChisel/ref/builtin_specifications.html#dnachisel.builtin_specifications.UniquifyAllKmers) is the generalized version of this? But I'm confused as to what values to use to match my use case (sorry, non-biologist here 😳).

Is it just `k = 10`, leaving `reference = None` and `location = None`?

**Comment by veghp** [comment]
Hi,
I believe you are looking for [HomopolymerPattern](https://edinburgh-genome-foundry.github.io/DnaChisel/ref/core_classes.html?highlight=repeat#homopolymerpattern): 
```python
pattern = HomopolymerPattern("A", 6)
constraint = AvoidPattern(pattern)
```

**Comment by lebolo** [comment]
Ahh, makes perfect sense! Thanks so much, I'll give it a shot.

**Comment by Zulko** [comment]
Just a note that you can also use `AvoidPattern("5x3mer")` for *"avoid a same 3-mer repeated 5 times in a row"*, and under this syntax you can avoid 8-homopolymers with  `AvoidPattern("8x1mer")` (but that's not the clearer notation). See here for the possible patterns:
 
https://edinburgh-genome-foundry.github.io/DnaChisel/genbank/genbank_api.html#id2
