### ISSUE TITLE
avoiding repeats

### ISSUE THREAD

**Issue by aaroncooper** [Edinburgh-Genome-Foundry/DnaChisel#47]
hey-- great module! I've been using to great effect for awhile now. one feature that'd really help out is repeat avoidance to be able to synthesize DNA at providers with fewer issues. is this possible in the package currently, or would it need to be built? thanks for developing and sharing this software!

**Comment by Zulko** [comment]
You can write `DnaOptimizationProblem(sequence, constraints=[AvoidPattern(pattern)])` where `pattern` can have different forms (see [this section](https://edinburgh-genome-foundry.github.io/DnaChisel/ref/core_classes.html#sequencepattern)). For direct repeats in particular you can write for instance `AvoidPattern("5x3mer")` to forbid 3-mers repeated 5 times in a row. Other  synthesis-impacting types of repeats can be destroyed with special classes such as `AvoidHairpins` and `UniquifyAllKmers` (to remove self-homologies).

**Comment by aaroncooper** [comment]
Thanks! I just started using this and it seems to work very well.
