### ISSUE TITLE
Unable to assign max_random_iters according to the demo example.

### ISSUE THREAD

**Issue by yech1990** [Edinburgh-Genome-Foundry/DnaChisel#5]
https://github.com/Edinburgh-Genome-Foundry/DnaChisel/blob/50bcd9a4f15228137cfd7f38377ca24eaaa63108/examples/features/example_max_random_iters.py#L23

This line will triggered the error.

However, `problem.max_random_iters = 10000` will work.

**Comment by Zulko** [comment]
Thanks for catching that, I have corrected the example :+1:
