### ISSUE TITLE
Uniquify all kmers when include_reverse_complement=False

### ISSUE THREAD

**Issue by seanrj-conagen** [Edinburgh-Genome-Foundry/DnaChisel#50]
It crashes due to:
`UnboundLocalError: local variable 'L' referenced before assignment`
Can be fixed by moving:
https://github.com/Edinburgh-Genome-Foundry/DnaChisel/blob/726b2b0254a8dbd9f51a78998cbb4e43cb096057/dnachisel/builtin_specifications/UniquifyAllKmers.py#L43

To above the if statement.

**Comment by lebolo** [comment]
Hi @seanrj-conagen, just FYI, @sukolsak opened PR #49 to fix this (and it was merged in)

**Comment by seanrj-conagen** [comment]
ok, thanks, I should just update. I must have an old version.

**Comment by lebolo** [comment]
Oh, his PR hasn't been released yet, just merged to develop (sorry, I'm just a nosy contributor, not a maintainer of this repo hehe)

**Comment by seanrj-conagen** [comment]
Oh, I see, that's funny, he saw the issue the same day!

**Comment by veghp** [comment]
Thanks -- now fixed in the [latest release](https://pypi.org/project/dnachisel/3.2.6/)
