### ISSUE TITLE
DnaChisel CLI - output to genbank not working

### ISSUE THREAD

**Issue by GC-repeat** [Edinburgh-Genome-Foundry/DnaChisel#57]
Hello,

when using the following command :
`>>> dnachisel annotated_record.gb optimized_record.gb`
I get the output below but although it says "Result written to optimized_record.gb" no file is created. 

> Before optimization:
>
 >===> FAILURE: 1 constraints evaluations failed
>✔PASS ┍ EnforceTranslation[0-507(+)]
>     │ Enforced by nucleotides restrictions
> FAIL ┍ AvoidPattern[0-507](pattern:EcoRI(GAATTC))
>     │ Failed. Pattern found at positions [493-499(+)]
>
>===> TOTAL OBJECTIVES SCORE:    -42.08
>    -42.08 ┍ MaximizeCAI[0-507(+)](5811) 
>           │ Codon opt. on window 0-507(+) scored -4.21E+01
>
>
> Resolving Constraints...
> Optimizing...                                                                                                                                                                                  
>                                                                                                                                                                                              
>                                                                                                                                                                                               
>After optimization:
>
> ===> SUCCESS - all constraints evaluations pass
>✔PASS ┍ EnforceTranslation[0-507(+)]
>     │ Enforced by nucleotides restrictions
>✔PASS ┍ AvoidPattern[0-507](pattern:EcoRI(GAATTC))
>      │ Passed. Pattern not found !
>
> ===> TOTAL OBJECTIVES SCORE:         0
>✔        0 ┍ MaximizeCAI[0-507(+)](5811) 
>          │ Codon opt. on window 0-507(+) scored -0.00E+00
>
> Result written to optimized_record.gb

The output files are created correctly if I use the other commands : 
`>>> dnachisel annotated_record.gb optimization_report/`
and
`>>> dnachisel annotated_record.gb optimization_report.zip`

The original genbank file is also processed correctly using the web app.

**Comment by veghp** [comment]
hi, thanks, I can confirm that the `optimized_record.gb` is not created. I'll have a look into it.

**Comment by veghp** [comment]
It's fixed in the `dev` branch now. Also added a `--with_sequence_edits` option to output Genbank files with annotated edits.
