### ISSUE TITLE
Make AvoidPattern() accept multiple patterns

### ISSUE THREAD

**Issue by chuanshangtingfeng** [Edinburgh-Genome-Foundry/DnaChisel#63]
Hi,
    When using DnaChisel, I try to set more than one pattern for AvoidPattern() like this, but it seems only the first one can be identified. Is there any way to make AvoidPattern() accept multiple patterns at the same time? 

problem = DnaOptimizationProblem(
    sequence=some_sequence,
    constraints=[
        **AvoidPattern("BsmBI_site", "BamHI_site")**,
        EnforceGCContent(mini=0.3, maxi=0.7, window=50),
        EnforceTranslation()
    ],
    objectives=[CodonOptimize(species='e_coli')]
)

**Comment by veghp** [comment]
You need to specify the patterns individually. Try
```python
constraints=[
    AvoidPattern("BsmBI_site"),
    AvoidPattern("BamHI_site"),
    EnforceGCContent(mini=0.3, maxi=0.7, window=50),
    EnforceTranslation()
]
```

**Comment by chuanshangtingfeng** [comment]
> You need to specify the patterns individually. Try
> 
> ```python
> constraints=[
>     AvoidPattern("BsmBI_site"),
>     AvoidPattern("BamHI_site"),
>     EnforceGCContent(mini=0.3, maxi=0.7, window=50),
>     EnforceTranslation()
> ]
> ```
Thank you !
