### ISSUE TITLE
dnachisel not working on AWS Lambda

### ISSUE THREAD

**Issue by guzmanvig** [Edinburgh-Genome-Foundry/DnaChisel#67]
Importing the library doesn't seem to work in AWS Lambda.

Something like the following:

```
import dnachisel as dc

def lambda_handler(event, context):  
    return "test"
```

When run on lambda throws:
```
{
  "errorMessage": "Unable to import module 'lambda_function': cannot import name '_aligners' from partially initialized module 'Bio.Align' (most likely due to a circular import) (/var/task/Bio/Align/__init__.py)",
  "errorType": "Runtime.ImportModuleError",
  "stackTrace": []
}
```

Everything works fine if I mock the lambda locally. I uploaded the lambda code and the dependencies as a zip file, but also tried uploading dnachisel as a lambda layer and got the same error.

Python version: 3.8
dnachisel version: 3.2.9

**Comment by Zulko** [comment]
Thanks for raising this. The error reads like it's triggered inside Biopython. Maybe using a different version of Biopython would resolve it? (e.g. `biopython==1.71`)

**Comment by guzmanvig** [comment]
Using `biopython==1.71` I get a new error 

```
No module named 'numpy.core._multiarray_umath'
```
Still works locally

**Comment by veghp** [comment]
I'm not familiar with AWS Lambda and that also means I cannot reproduce the error. A few things perhaps you can try:
make sure that there is no `lambda_function.py` or some files with the same name as the imported module in your working directory. Similarly that there are no parallel installations of Bio or dnachisel (e.g. pip and conda). Restarting the whole virtual environment and starting from scratch may also help.

It works locally for you and it [passes CI](https://app.travis-ci.com/github/Edinburgh-Genome-Foundry/DnaChisel) (and the MotifPssmPattern module is tested) so it's unlikely that the packages are wrong.

You can try using the previous version (3.2.8) and also biopython==1.78. Note that EGF packages were developed on Python 3.6 and now I'm working to ensure that they all work on Python 3.9.

**Comment by guzmanvig** [comment]
Thanks for the suggestions. As I'm trying to make it work, the set up is really simple, only a file named `lambda_function.py` with the code I showed above. When AWS Lambda runs, it creates its own environment from scratch so the issue is not likely there.

I've tried all the combinations with the versions you mentioned and still no luck.

If you want to try reproduce this, the simplest way is to upload the code as a zip file and run it (see "Deployment package with dependencies" at https://docs.aws.amazon.com/lambda/latest/dg/python-package.html)

Thanks!

**Comment by veghp** [comment]
I have one more suggestion. I believe this problem is not related to DNA Chisel, but Biopython.

When we import `/site-packages/Bio/Align/__init__.py` it starts with
```python
import sys

from Bio.Align import _aligners
```
which is the line that causes problem according to your error. This is an .so file, and these discussions suggest "Problem is solved by deploying the package through AWS codeBuild":

https://stackoverflow.com/questions/64450587/error-trying-to-import-pysftp-in-lambda-cannot-import-name-bcrypt-from-parti

https://github.com/pymupdf/PyMuPDF/issues/430#issuecomment-576231408

**Comment by guzmanvig** [comment]
Unfortunately we can't use code build as it would imply changing the whole infrastructure of our project. However, you are right, the problem is with biopython. 
I tried the following code and got the same issue.
```
from Bio.Align import _aligners

def lambda_handler(event, context):
    return "test"
```

Thank you!
