### ISSUE TITLE
Issue when importing as of Nov. 28, 2022

### ISSUE THREAD

**Issue by nothinginbiology** [Edinburgh-Genome-Foundry/DnaChisel#70]
Seems to be an error with dna_features_viewer or something. Can't import module.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-11-8db00091b731>](https://localhost:8080/#) in <module>
----> 1 from goldenhinges import OverhangsSelector, OverhangsSelector
      2 import dnachisel
      3 import geneblocks
      4 from dnachisel import (EnforceTranslation, Specification, SpecEvaluation,
      5                        reverse_translate, random_protein_sequence, Location,

5 frames
[/usr/local/lib/python3.7/dist-packages/dna_features_viewer/biotools.py](https://localhost:8080/#) in <module>
     36 
     37 aa_short_to_long_form_dict = {
---> 38     _aa1: _aa3[0] + _aa3[1:].lower() for (_aa1, _aa3) in zip(aa1 + "*", aa3 + ["*"])
     39 }
     40 

TypeError: can only concatenate tuple (not "str") to tuple

**Comment by veghp** [comment]
Thank you, yes it has been reported there and will be addressed: https://github.com/Edinburgh-Genome-Foundry/DnaFeaturesViewer/issues/73

[Temporary solutions](https://github.com/Edinburgh-Genome-Foundry/DnaFeaturesViewer/issues/73#issuecomment-1324019770)

**Comment by veghp** [comment]
This has been fixed upstream now and works with the latest Biopython. An additional matplotlib error has been fixed in the latest version, 3.2.10.
