### ISSUE TITLE
Constraints vs Objectives differences

### ISSUE THREAD

**Issue by DomML** [Edinburgh-Genome-Foundry/DnaChisel#78]
Hi,
I'm not sure to understand the difference between constraints and objective in DnaOptimizationProblem.
Best,
DomML.

**Comment by veghp** [comment]
From the [publication](https://academic.oup.com/bioinformatics/article/36/16/4508/5869515): _"A specification can be either a hard **constraint, which must be satisfied** in the final sequence, or an **optimization objective, whose score must be maximized**. For instance, specification AvoidChanges can be used as a constraint to forbid sequence modifications in a given region, or as an objective to simply penalize changes in that region. In presence of multiple optimization objectives, which can be attributed relative weights, DNA Chisel will seek to maximize the total weighted score using the heuristics described in the next section (an example of multi-objective gene optimization is provided in [Supplementary Section S1B]."_

Thank you for bringing attention to this, a link to the publication will be added to the readme soon.
