### ISSUE TITLE
Avoiding N-length codon sequences

### ISSUE THREAD

**Issue by kmcgrathgenerate** [Edinburgh-Genome-Foundry/DnaChisel#79]
I am trying to avoid a set of codon sub-sequences in a larger sequence. I am setting this as a constraint. I am unable to use the existing BaseCodonOptimizationClass get_codons(); it requires me to use my own "get_codons" function that always returns the full sequence. Since the sequence I am trying to avoid can only appear in a combination of N codons in order, is there a way to support this using the base codon optimization class? I worry that returning locations that are outside of the range the evaluate is using will cause big problems. 

```
def evaluate(self, problem):  # pylint:disable=method-hidden
        "Score is the number of offending codons"
        if not any(subsequence in problem.sequence for subsequence in self.subsequences):
            return SpecEvaluation(self, problem, score=0, locations=[], message="All OK.")
        codons = self.get_codons(problem)
        subseq_indices = set()
        for index in range(len(codons) - 2):
            tricodon = "".join(codons[index : index + 3])
            if tricodon in self.subsequences:
                subseq_indices(range(index, index + 3))

        subseq_indices_list = list(subseq_indices)
        locations = self.codons_indices_to_locations(subseq_indices_list)
        score = -len(subseq_indices_list)
        return SpecEvaluation(
            self,
            problem,
            score=score,
            locations=locations,
            message=("All OK." if len(locations) == 0 else f”subsequence in sequence”),
        )
```

I should mention that when returning the full sequence in every evaluate, the optimization works.

**Comment by Zulko** [comment]
Have you tried using `AvoidPattern` in addition to `CodonOptimize` (not as part of the same class)? Would this work for you?

```python
constraints=[EnforceTranslation(), AvoidPattern("ATGCGCACAC"), ...]
objectives=[CodonOptimize("e_coli")]
```

**Comment by kmcgrathgenerate** [comment]
Should have mentioned that the location of where these subsequences fall is important. I think this will just have to create a custom get codons and get indices function. it works fine this way
